import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})

export const metadata: Metadata = {
  metadataBase: new URL("https://viabetel.com"),
  title: {
    default: "Via Betel - Instrutores de Condução | Aulas de Direção em Juiz de Fora e Minas Gerais",
    template: "%s | Via Betel - Instrutores de Condução",
  },
  description:
    "Encontre instrutores de direção qualificados em Juiz de Fora e região. Via Betel conecta alunos e instrutores certificados para aulas práticas de direção, reforço CNH, treino para prova prática e aperfeiçoamento ao volante em todas as categorias (A, B, C, D, E).",
  keywords: [
    "auto escola",
    "auto escola digital",
    "auto escola online",
    "aulas de direção",
    "aulas de carro",
    "aulas de moto",
    "instrutor de direção",
    "instrutores certificados",
    "instrutor particular",
    "professor de direção",
    "carteira de motorista",
    "CNH",
    "habilitação",
    "primeira habilitação",
    "tirar CNH",
    "tirar carteira de motorista",
    "renovar CNH",
    "aulas práticas",
    "aulas práticas de direção",
    "direção defensiva",
    "direção segura",
    "curso de direção",
    "aprender a dirigir",
    "como tirar CNH",
    "categoria A",
    "categoria B",
    "categoria C",
    "categoria D",
    "categoria E",
    "CNH categoria A",
    "CNH categoria B",
    "habilitação categoria A",
    "habilitação categoria B",
    "aula de moto",
    "aula de carro manual",
    "aula de carro automático",
    "Via Betel",
    "auto escola Minas Gerais",
    "auto escola MG",
    "auto escola Belo Horizonte",
    "auto escola Contagem",
    "instrutor Belo Horizonte",
    "instrutor Contagem",
    "aulas de direção BH",
    "aulas de direção Minas Gerais",
    "plataforma auto escola",
    "app auto escola",
    "melhor auto escola",
    "auto escola perto de mim",
    "instrutor perto de mim",
    "agendar aula de direção",
    "marcar aula prática",
    "preço aula de direção",
    "valor aula particular",
    "DETRAN MG",
    "DENATRAN",
    "código de trânsito",
    "legislação de trânsito",
    "segurança viária",
    "educação no trânsito",
    "mobilidade urbana",
    "trânsito seguro",
    "Via Betel",
    "Via Betel Auto Escola",
    "Via Betel Instrutores",
    "instrutores de condução",
    "instrutores de direção",
    "plataforma instrutores",
    "instrutor em juiz de fora",
    "instrutor juiz de fora",
    "instrutor de direção juiz de fora",
    "instrutor particular de direção juiz de fora",
    "instrutor de autoescola juiz de fora",
    "instrutor de trânsito juiz de fora",
    "professor de direção juiz de fora",
    "melhor instrutor de direção juiz de fora",
    "instrutor de direção perto de mim juiz de fora",
    "instrutor particular perto de mim juiz de fora",
    "instrutor credenciado juiz de fora",
    "instrutor autônomo juiz de fora",
    "instrutor MEI juiz de fora",
    "aula de direção juiz de fora",
    "aulas de direção juiz de fora",
    "aula prática de direção juiz de fora",
    "aulas práticas CNH juiz de fora",
    "aula particular de direção juiz de fora",
    "aulas extras CNH juiz de fora",
    "aula de direção perto de mim juiz de fora",
    "preço aula de direção juiz de fora",
    "quanto custa aula de direção juiz de fora",
    "valor aula prática CNH juiz de fora",
    "aula de volante juiz de fora",
    "aula ao volante juiz de fora",
    "reforço para prova prática juiz de fora",
    "treino para prova prática juiz de fora",
    "treino para exame do detran juiz de fora",
    "treino de baliza juiz de fora",
    "treino de rampa juiz de fora",
    "treino de estacionamento juiz de fora",
    "treinamento de direção juiz de fora",
    "reforço CNH juiz de fora",
    "como fazer baliza juiz de fora",
    "como passar na prova prática juiz de fora",
    "erros na prova prática detran juiz de fora",
    "aula de direção noturna juiz de fora",
    "aula de direção para habilitados juiz de fora",
    "aula para quem tem CNH e não dirige juiz de fora",
    "medo de dirigir juiz de fora",
    "ansiedade para dirigir juiz de fora",
    "voltar a dirigir juiz de fora",
    "aperfeiçoamento ao volante juiz de fora",
    "direção defensiva juiz de fora",
    "direção na chuva juiz de fora",
    "direção em rodovia juiz de fora",
    "direção no centro de juiz de fora",
    "aula de direção carro manual juiz de fora",
    "aula de direção carro automático juiz de fora",
    "controle de embreagem juiz de fora",
    "ponto de embreagem juiz de fora",
    "carro morrendo na saída juiz de fora",
    "arrancada em rampa juiz de fora",
    "troca de marcha juiz de fora",
    "noção de espaço ao dirigir juiz de fora",
    "autoescola em juiz de fora",
    "auto escola em juiz de fora",
    "cfc juiz de fora",
    "centro de formação de condutores juiz de fora",
    "autoescola juiz de fora",
    "auto escola juiz de fora",
    "CNH juiz de fora",
    "carteira de motorista juiz de fora",
    "habilitação juiz de fora",
    "tirar CNH juiz de fora",
    "primeira habilitação juiz de fora",
    "primeira CNH juiz de fora",
    "renovação CNH juiz de fora",
    "CNH definitiva juiz de fora",
    "CNH provisória juiz de fora",
    "PPD juiz de fora",
    "CNH digital juiz de fora",
    "CDT carteira digital de trânsito juiz de fora",
    "CNH A juiz de fora",
    "CNH B juiz de fora",
    "CNH AB juiz de fora",
    "CNH C juiz de fora",
    "CNH D juiz de fora",
    "CNH E juiz de fora",
    "habilitação moto juiz de fora",
    "habilitação carro juiz de fora",
    "adição de categoria CNH juiz de fora",
    "mudança de categoria CNH juiz de fora",
    "inclusão EAR juiz de fora",
    "EAR na CNH juiz de fora",
    "detran juiz de fora",
    "detran mg juiz de fora",
    "prova teórica CNH juiz de fora",
    "prova prática CNH juiz de fora",
    "simulado prova CNH juiz de fora",
    "legislação de trânsito juiz de fora",
    "taxas detran mg juiz de fora",
    "agendamento detran mg juiz de fora",
    "aula de direcao juiz de fora",
    "aulas de direcao juiz de fora",
    "carteira de motorista juiz de fora",
    "habilitacao juiz de fora",
    "detran juiz de fora mg",
    "prova pratica cnh juiz de fora",
    "prova teorica cnh juiz de fora",
    "instrutor particular de direcao juiz de fora",
    "instrutor de direcao juiz de fora",
    "aulas de direção JF",
    "instrutor JF",
    "CNH JF",
    "autoescola JF",
    "carteira de motorista JF",
    "habilitação JF",
    "detran JF",
    "juiz de fora MG",
    "juiz de fora minas gerais",
    "juiz de fora zona da mata",
    "zona da mata mg instrutor",
    "instrutor em minas gerais",
    "aula de direção minas gerais",
    "instrutor de direção minas gerais",
    "instrutor em juiz de fora mg",
    "aula de direção em juiz de fora mg",
    "carteira de motorista em juiz de fora mg",
    "instrutor em juiz de fora sem acento",
    "instrutor em juiz de fora mg sem acento",
    "instrutor em juiz de fora centro",
    "instrutor centro juiz de fora",
    "aula de direção centro juiz de fora",
    "instrutor são mateus juiz de fora",
    "aula de direção são mateus juiz de fora",
    "instrutor santa helena juiz de fora",
    "aula de direção santa helena juiz de fora",
    "instrutor bom pastor juiz de fora",
    "aula de direção bom pastor juiz de fora",
    "instrutor alto dos passos juiz de fora",
    "aula de direção alto dos passos juiz de fora",
    "instrutor manoel honório juiz de fora",
    "aula de direção manoel honório juiz de fora",
    "instrutor benfica juiz de fora",
    "aula de direção benfica juiz de fora",
    "instrutor são pedro juiz de fora",
    "aula de direção são pedro juiz de fora",
    "instrutor jardim glória juiz de fora",
    "aula de direção jardim glória juiz de fora",
    "instrutor granbery juiz de fora",
    "aula de direção granbery juiz de fora",
    "instrutor paineiras juiz de fora",
    "aula de direção paineiras juiz de fora",
    "instrutor cascatinha juiz de fora",
    "aula de direção cascatinha juiz de fora",
    "instrutor mariano procópio juiz de fora",
    "aula de direção mariano procópio juiz de fora",
    "instrutor nova era juiz de fora",
    "aula de direção nova era juiz de fora",
    "instrutor teixeiras juiz de fora",
    "aula de direção teixeiras juiz de fora",
    "instrutor retiro juiz de fora",
    "aula de direção retiro juiz de fora",
    "instrutor linhares juiz de fora",
    "aula de direção linhares juiz de fora",
    "instrutor olavo costa juiz de fora",
    "aula de direção olavo costa juiz de fora",
    "instrutor democrata juiz de fora",
    "aula de direção democrata juiz de fora",
    "instrutor grama juiz de fora",
    "aula de direção grama juiz de fora",
    "instrutor salvaterra juiz de fora",
    "aula de direção salvaterra juiz de fora",
    "CNH BRASIL",
    "carteira de motorista brasil",
    "tirar CNH brasil",
    "instrutor de direção brasil",
    "instrutor de autoescola brasil",
    "prova prática detran mg",
    "prova teórica detran mg",
    "senatran CNH",
    "código de trânsito brasileiro",
    "CTB trânsito",
    "contran CNH",
    "auto escola",
    "auto escola digital",
    "auto escola online",
    "aulas de direção",
    "aulas de carro",
    "aulas de moto",
    "carteira de motorista",
    "CNH",
    "habilitação",
    "primeira habilitação",
    "tirar CNH",
    "renovar CNH",
    "aulas práticas",
    "direção defensiva",
    "direção segura",
    "curso de direção",
    "aprender a dirigir",
    "categoria A",
    "categoria B",
    "categoria C",
    "categoria D",
    "categoria E",
    "DETRAN",
    "DENATRAN",
    "código de trânsito",
    "legislação de trânsito",
  ],
  authors: [{ name: "Via Betel - Instrutores de Condução" }],
  creator: "Via Betel",
  publisher: "Via Betel - Instrutores de Condução",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  generator: "Next.js",
  applicationName: "Via Betel - Instrutores de Condução",
  referrer: "origin-when-cross-origin",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: "/apple-touch-icon.jpg",
  },
  alternates: {
    canonical: "https://viabetel.com/",
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://viabetel.com/",
    siteName: "Via Betel - Instrutores de Condução",
    title: "Via Betel - Instrutores de Condução | Aulas de Direção em Juiz de Fora e MG",
    description:
      "Encontre os melhores instrutores de direção em Juiz de Fora e região. Aulas práticas, reforço CNH, treino para prova prática. Conectamos alunos e instrutores certificados!",
    images: [
      {
        url: "/images/viabetel-og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Via Betel - Instrutores de Condução | Juiz de Fora e Minas Gerais",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Via Betel - Instrutores de Condução | Aulas de Direção em Juiz de Fora",
    description:
      "Encontre instrutores certificados em Juiz de Fora. Aulas práticas, reforço CNH e treino para prova. Conquiste sua habilitação!",
    images: ["/images/viabetel-og-image.jpg"],
  },
  verification: {
    google: "google-site-verification-code",
  },
  other: {
    "geo.region": "BR-MG",
    "geo.placename": "Juiz de Fora, Minas Gerais",
    "og:locale:alternate": "pt_BR",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" className={inter.variable}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
      </head>
      <body className="font-sans bg-neutral-50 text-neutral-900 overflow-x-hidden antialiased">{children}</body>
    </html>
  )
}
